version: '3.9'
services:
  consumer:
    build:
      context: .
      dockerfile: apps/consumer/Dockerfile
    env_file:
      - apps/consumer/.env
    networks:
      - app-net
    deploy:
      replicas: 5
   
  producer:
    build:
      context: .
      dockerfile: apps/producer/Dockerfile
    env_file:
      - apps/producer/.env
    networks:
      - app-net
    ports: 
      - 3001:3001
 
   
networks:
  app-net:
    driver: bridge